# -*- coding: utf-8 -*-
"""24EE65R14_assignment_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SSbpByb-msTkfbAdKFYfjysMPnCBAt7Q
"""

# installation of required packages - portallocker, torchtext, torchinfo,---
!pip -q install portalocker
!pip install -q torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
!pip install -q torchtext==0.15.2
!pip install -q torchinfo

from torchtext.datasets import AG_NEWS
train_data, test_data = AG_NEWS(split=('train', 'test'))

# Convert to list to get length
train_length = sum(1 for _ in train_data)
test_length = sum(1 for _ in test_data)

print("Train data length:", train_length)
print("Test data length:", test_length)

for i, sample in enumerate(train_data):
    if i == 3:  # Show only 3 samples
        break
    print(sample)  # Each sample is a tuple (label, text)

import nltk
nltk.download('punkt', force=True)
nltk.download('stopwords', force=True)

import torchtext
import string
from torchtext.datasets import AG_NEWS
from torchtext.vocab import build_vocab_from_iterator
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset, TensorDataset
from torchinfo import summary  # For displaying summary of model
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import matplotlib.pyplot as plt

import nltk
nltk.download('punkt')

import nltk
print(nltk.data.path)

ls -R /home/guest/nltk_data/tokenizers/

import nltk
nltk.data.path.append('/home/guest/nltk_data')  # Ensure it looks in the right directory

import torch
import string
import nltk
from torchtext.datasets import AG_NEWS
from torchtext.vocab import build_vocab_from_iterator
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.data.path.append('/home/guest/nltk_data')
nltk.download('punkt', download_dir='/home/guest/nltk_data')
nltk.download('stopwords', download_dir='/home/guest/nltk_data')
nltk.download('punkt_tab', download_dir='/home/guest/nltk_data')

# Define stopwords and punctuation set
stop_words = set(stopwords.words('english'))
punctuations = set(string.punctuation)

# Load dataset and store it in lists
train_data = list(AG_NEWS(split='train'))
test_data = list(AG_NEWS(split='test'))

# Preprocessing function
def preprocess_text(text):
    tokens = word_tokenize(text.lower())  # Tokenization & lowercase
    tokens = [word for word in tokens if word not in stop_words and word not in punctuations]  # Remove stopwords & punctuation
    return tokens

# Build vocabulary from training dataset
def yield_tokens(data_iter):
    for _, text in data_iter:
        yield preprocess_text(text)

# Reload dataset for iteration
train_data, test_data = AG_NEWS(split=('train', 'test'))
vocab = build_vocab_from_iterator(yield_tokens(train_data), specials=["<unk>"])
vocab.set_default_index(vocab["<unk>"])

# Numerical encoding function
def numericalize(text):
    return vocab(preprocess_text(text))

# Process dataset
processed_train = [(label, numericalize(text)) for label, text in train_data]
processed_test = [(label, numericalize(text)) for label, text in test_data]

# Show 3 samples
for i in range(3):
    print(processed_train[i])

import torch
import random

# Define max length and padding token
MAX_LEN = 256
PAD_TOKEN = 0  # Assuming the padding token index is 0

# Combine train and test sets
full_data = processed_train
random.shuffle(full_data)  # Shuffle before splitting

# Split training dataset: 80% train, 20% validation
train_size = int(0.8 * len(full_data))
val_size = int(0.2 * len(full_data))

train_data = full_data[:train_size]
val_data = full_data[train_size:]
test_data = processed_test[:]

# Function to apply padding
def pad_sequence(seq, max_len=MAX_LEN):
    seq = torch.tensor(seq) if not isinstance(seq, torch.Tensor) else seq  # Ensure tensor
    if len(seq) < max_len:
        seq = torch.cat([seq, torch.full((max_len - len(seq),), PAD_TOKEN, dtype=torch.long)])
    else:
        seq = seq[:max_len]
    return seq

# Apply padding
processed_train = [(label, pad_sequence(text)) for label, text in train_data]
processed_val = [(label, pad_sequence(text)) for label, text in val_data]
processed_test = [(label, pad_sequence(text)) for label, text in test_data]

# Show 3 samples
for i in range(3):
    print(processed_train[i])

# Extract labels from all datasets
all_labels = {label for label, _ in processed_train} | \
             {label for label, _ in processed_val} | \
             {label for label, _ in processed_test}

# Print unique labels
print("Unique labels:", all_labels)

# Function to re-encode labels
def encode_label(label):  # Convert 1 → 0 , 2 → 1 ,  3 → 2 , 4 → 3

        if label == 1:
            return 0
        elif label == 2:
            return 1
        elif label == 3:
            return 2
        elif label == 4:
            return 3
        else:
            return -1  # or raise an error for unexpected labels
# Apply label encoding
processed_train = [(encode_label(label), text) for label, text in processed_train]
processed_val = [(encode_label(label), text) for label, text in processed_val]
processed_test = [(encode_label(label), text) for label, text in processed_test]

# Verify unique labels after encoding
all_labels = {label for label, _ in processed_train} | \
             {label for label, _ in processed_val} | \
             {label for label, _ in processed_test}

print("Unique labels after encoding:", all_labels)

from collections import Counter
import matplotlib.pyplot as plt

# Count occurrences of each class
def plot_class_distribution(data, title):
    labels = [label for label, _ in data]
    class_counts = Counter(labels)

    plt.bar(class_counts.keys(), class_counts.values(), tick_label=["World", "Sports", "Business", "Sci/Tech"])
    plt.xlabel("Classes")
    plt.ylabel("Frequency")
    plt.title(title)
    plt.show()

# Plot for train and validation sets
plot_class_distribution(train_data, "Class Distribution in Train Set")

# Hyperparameters
EMBED_DIM = 128
HIDDEN_DIM = 256
NUM_LAYERS = 2
NUM_CLASSES = 4  # Since we have labels {0,1}
BATCH_SIZE = 32
DROPOUT_PROB=0.25
EPOCHS = 8
VOCAB_SIZE = len(vocab)  # Vocabulary size

VOCAB_SIZE

import torch
import torch.nn as nn

# Define GRU Model with Two Layers using nn.GRUCell
class GRUCell(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, num_classes, dropout_prob):
        super(GRUCell, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.gru1 = nn.GRUCell(embedding_dim, hidden_dim)
        self.gru2 = nn.GRUCell(hidden_dim, hidden_dim)
        self.dropout = nn.Dropout(dropout_prob)
        self.fc = nn.Linear(hidden_dim, num_classes)

    def forward(self, x):
        embedded = self.embedding(x)
        h1 = torch.zeros(x.size(0), self.gru1.hidden_size, device=x.device)
        h2 = torch.zeros(x.size(0), self.gru2.hidden_size, device=x.device)

        for i in range(x.size(1)):  # Iterate over sequence length
            h1 = self.gru1(embedded[:, i, :], h1)
            h1 = self.dropout(h1)
            h2 = self.gru2(h1, h2)

        return self.fc(h2)

# Convert data to tensors
from torch.utils.data import DataLoader, TensorDataset

def create_dataloader(processed_data, batch_size):
    labels = torch.tensor([label for label, _ in processed_data], dtype=torch.long)
    sequences = torch.stack([text for _, text in processed_data])  # Stack tensors
    dataset = TensorDataset(sequences, labels)
    return DataLoader(dataset, batch_size=batch_size, shuffle=True)

# Create DataLoaders
train_loader = create_dataloader(processed_train, BATCH_SIZE)
val_loader = create_dataloader(processed_val, BATCH_SIZE)
test_loader = create_dataloader(processed_test, BATCH_SIZE)

# Define model, loss, and optimizer
vocab_size = len(vocab)  # Change this based on your vocab size
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

device

model = GRUCell(vocab_size, EMBED_DIM, HIDDEN_DIM,NUM_CLASSES,DROPOUT_PROB).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-5)

print(model)

import matplotlib.pyplot as plt

# Training loop with loss visualization
def train_model(model, train_loader, val_loader, epochs):
    model.train()
    train_losses, val_losses = [], []

    for epoch in range(epochs):
        total_train_loss = 0
        model.train()  # Ensure model is in training mode

        for batch_x, batch_y in train_loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)

            optimizer.zero_grad()
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()

            total_train_loss += loss.item()

        # Compute validation loss
        model.eval()  # Switch to evaluation mode
        total_val_loss = 0
        with torch.no_grad():
            for batch_x, batch_y in val_loader:
                batch_x, batch_y = batch_x.to(device), batch_y.to(device)
                outputs = model(batch_x)
                loss = criterion(outputs, batch_y)
                total_val_loss += loss.item()

        # Calculate average loss
        avg_train_loss = total_train_loss / len(train_loader)
        avg_val_loss = total_val_loss / len(val_loader)
        train_losses.append(avg_train_loss)
        val_losses.append(avg_val_loss)

        print(f"Epoch [{epoch+1}/{epochs}], Train Loss: {avg_train_loss:.4f}, Val Loss: {avg_val_loss:.4f}")

    print("Training complete.")

    # Plot loss variation
    plt.figure(figsize=(8, 5))
    plt.plot(range(1, epochs + 1), train_losses, label="Training Loss")
    plt.plot(range(1, epochs + 1), val_losses, label="Validation Loss")
    plt.xlabel("Epochs")
    plt.ylabel("Loss")
    plt.legend()
    plt.title("Training & Validation Loss Over Epochs")
    plt.show()

# Train the model
train_model(model, train_loader, val_loader, EPOCHS)

# Fetch one batch from train_loader
actual_input, _ = next(iter(train_loader))  # Get batch_x (ignore batch_y)

# Ensure the input is of type LongTensor
actual_input = actual_input.to(dtype=torch.long, device=device)

# Display model summary
summary(model, input_data=actual_input, col_names=["input_size", "output_size", "num_params", "trainable"])

from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix

# Function to evaluate model performance
def evaluate_model(model, data_loader):
    model.eval()
    correct, total = 0, 0
    all_preds = []   # initializing the lists
    all_labels = []

    with torch.no_grad():
        for batch_x, batch_y in data_loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            outputs = model(batch_x)
            _, predicted = torch.max(outputs, 1)

            # Store predictions and actual labels
            all_preds.extend(predicted.cpu().tolist())  # Use .tolist()
            all_labels.extend(batch_y.cpu().tolist())

            correct += (predicted == batch_y).sum().item()
            total += batch_y.size(0)

    # Compute accuracy
    accuracy = correct / total

    # Compute precision, recall, and F1-score
    precision = precision_score(all_labels, all_preds, average="weighted", zero_division=0)
    recall = recall_score(all_labels, all_preds, average="weighted", zero_division=0)
    f1 = f1_score(all_labels, all_preds, average="weighted", zero_division=0)
    conf_matrix = confusion_matrix(all_labels, all_preds)

    print(f"Accuracy:  {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall:    {recall:.4f}")
    print(f"F1-score:  {f1:.4f}")
    print("Confusion Matrix:\n", conf_matrix)

# Evaluate on test set
evaluate_model(model, test_loader)

import torch
import torch.nn as nn

# Define GRU Model with Two Layers using nn.GRU
class GRU(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, num_classes, dropout_prob):
        super(GRU, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.gru1 = nn.GRU(embedding_dim, hidden_dim, batch_first=True)
        self.gru2 = nn.GRU(hidden_dim, hidden_dim, batch_first=True)
        self.dropout = nn.Dropout(dropout_prob)
        self.fc = nn.Linear(hidden_dim, num_classes)

    def forward(self, x):
        embedded = self.embedding(x)
        h1 = torch.zeros(1, x.size(0), self.gru1.hidden_size, device=x.device)
        out, _ = self.gru1(embedded, h1)
        out = self.dropout(out)
        h2 = torch.zeros(1, x.size(0), self.gru2.hidden_size, device=x.device)
        out, _ = self.gru2(out, h2)
        # Take the last hidden state
        out = out[:, -1, :]
        return self.fc(out)

model1 = GRU(vocab_size, EMBED_DIM, HIDDEN_DIM,NUM_CLASSES,DROPOUT_PROB).to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model1.parameters(), lr=0.001, weight_decay=1e-5)

print(model1)

EPOCHS1=5

# Train the model
train_model(model1, train_loader, val_loader, EPOCHS1)

# Evaluate on test set
evaluate_model(model1, test_loader)

# Display model summary
summary(model1, input_data=actual_input, col_names=["input_size", "output_size", "num_params", "trainable"])

